### ISSUE TITLE
error getting directory

### ISSUE THREAD

**Issue by DZY90** [DxCx/plugin.video.9anime#148]
18:57:58.824 T:9440   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.9anime/
18:57:58.827 T:9440   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.9anime/) failed
19:11:47.530 T:9440   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
19:11:48.043 T:1016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named urllib3
                                            Traceback (most recent call last):
                                              File "C:\Users\Darryl\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py", line 1, in <module>
                                                from resources.lib.ui import control
                                              File "C:\Users\Darryl\AppData\Roaming\Kodi\addons\plugin.video.9anime\resources\lib\ui\control.py", line 7, in <module>
                                                import http
                                              File "C:\Users\Darryl\AppData\Roaming\Kodi\addons\plugin.video.9anime\resources\lib\ui\http.py", line 2, in <module>
                                                from http_imports import *
                                              File "C:\Users\Darryl\AppData\Roaming\Kodi\addons\plugin.video.9anime\resources\lib\ui\http_imports.py", line 12, in <module>
                                                import requests
                                              File "C:\Users\Darryl\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\__init__.py", line 43, in <module>
                                                import urllib3
                                            ImportError: No module named urllib3

**Comment by DZY90** [comment]
NVM I uninstalled kodi then reinstalled it's back working
