### ISSUE TITLE
Unable to play when list episodes as directory

### ISSUE THREAD

**Issue by ypawar159** [DxCx/plugin.video.9anime#204]
Addon gives following error when display episode list as directory is selected.

12:57:51.392 T:6472   ERROR: InputStream: Error opening, plugin://plugin.video.9anime/play/agent-aika-dub.km4w/1
12:58:30.201 T:3560  NOTICE: URLResolver: Initializing URLResolver version: 3.0.31
12:58:30.213 T:3560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: cannot concatenate 'str' and 'function' objects
                                            Traceback (most recent call last):
                                              File "C:\Users\yogesh.pawar\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py", line 162, in <module>
                                                router_process(control.get_plugin_url())
                                              File "C:\Users\yogesh.pawar\AppData\Roaming\Kodi\addons\plugin.video.9anime\resources\lib\ui\router.py", line 39, in router_process
                                                return route_obj.func(payload)
                                              File "C:\Users\yogesh.pawar\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py", line 149, in PLAY
                                                items = map(lambda x: utils.allocate_item(x[0], 'playlink&url=/'+x[1], False, ''), items)
                                              File "C:\Users\yogesh.pawar\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py", line 149, in <lambda>
                                                items = map(lambda x: utils.allocate_item(x[0], 'playlink&url=/'+x[1], False, ''), items)
                                            TypeError: cannot concatenate 'str' and 'function' objects
                                            -->End of Python script error report<--
12:58:30.347 T:3560 WARNING: CPythonInvoker(18, C:\Users\yogesh.pawar\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py): the python script "C:\Users\yogesh.pawar\AppData\Roaming\Kodi\addons\plugin.video.9anime\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
12:58:30.377 T:5592   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.9anime/play/agent-aika-dub.km4w/1
12:58:30.380 T:5592   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.9anime/play/agent-aika-dub.km4w/1) failed

**Comment by ypawar159** [comment]
Another observation is that if directory view is selected then in context menu for episode there is no play option. This may be helpful.

**Comment by ypawar159** [comment]
@DxCx ,
Adding logger I found that the contents of items have following:
Sources: {u'01 | RapidVideo (720p)': <function playSource at 0x11B5B170>, u'02 | RapidVideo (360p)': <function playSource at 0x11B3BFB0>}

This playSource  function, I wonder from where it is coming?

**Comment by ypawar159** [comment]
@DxCx ,
Solved this issue with small code change (took all day to figure it out though).
The PR is #207 . Please merge this asap, as download feature development is stuck because of this.

**Comment by ypawar159** [comment]
@DxCx 
Created new PR #209 .
